a="31.2"
b = float(a)
t= type(b)
print(t)
  
#  THE CONVERSIONS OF THESE ARE AS FOLLOWS:

# str(31) INTEGER TO STRING CONVERSION 
# int("32") STRING TO INTEGER CONVERSION
# float(32) INTEGER TO FLOAT CONVERSION
